#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postinst"
LOG="/var/log/xwhep-worker.log"
INSTALLDIR="/opt/xwhep-worker-@XWVERSION@"
BINDIR="${INSTALLDIR}/bin"
CONFDIR="${INSTALLDIR}/conf"
CONFILE=$CONFDIR/xtremweb.worker.conf
PROG="xtremweb.worker"
INITD="/etc/init.d"
SYSLOGIN=@XWUSER@

USRBIN=/usr/bin
USRLOCALBIN=/usr/local/bin
USRBINXWCREATEVDI=$USRBIN/xwcreatevdi
USRLOCALBINCREATEVDI=$USRLOCALBIN/createvdi
CREATEVDI=${BINDIR}/createvdi

SUDOERS=/etc/sudoers
SUDOERSD="${SUDOERS}.d"
XWHEPSUDOERS="${SUDOERSD}/99-xwhep"
SUDOERSFILE=${SUDOERS}

SUDOERSENTRY="${SYSLOGIN} ALL=NOPASSWD: ${USRBINXWCREATEVDI}"
SUDOERSENTRY2="${SYSLOGIN} ALL=NOPASSWD: ${USRLOCALBINCREATEVDI}"

VBAPPNAME="virtualbox"
VBHL="/usr/bin/vboxheadless"
DOCKERAPPNAME="docker"
DOCKERPATH="/usr/local/bin/docker"

[ -d ${SUDOERSD} ] && SUDOERSFILE=${XWHEPSUDOERS}

touch ${LOG}
date >> ${LOG}  2>&1 
echo "XtemWeb-HEP ${PROG} ${WHAT} @XWVERSION@" >> ${LOG}  2>&1
#date >> ${LOG}  2>&1
#ln -s ${BINDIR}/${PROG} /etc/init.d/${PROG} >> ${LOG}  2>&1
#/etc/init.d/${PROG} start >> ${LOG}  2>&1

rm -f ${INITD}/${PROG} >> ${LOG}  2>&1
ln -s ${BINDIR}/${PROG} ${INITD}/${PROG} >> ${LOG}  2>&1

rm -f ${USRBINXWCREATEVDI} >> ${LOG}  2>&1 
ln -s ${CREATEVDI} ${USRBINXWCREATEVDI} >> ${LOG}  2>&1 
ln -s ${CREATEVDI} $USRLOCALBINCREATEVDI >> ${LOG}  2>&1 

if [ "X${SYSLOGIN}" != "X" ] ; then 
    chown -R ${SYSLOGIN}.${SYSLOGIN} ${INSTALLDIR} >> ${LOG}  2>&1
    chown -R ${SYSLOGIN}.${SYSLOGIN} ${USRBINXWCREATEVDI} >> ${LOG}  2>&1
	if [ -f ${SUDOERSFILE} ] ; then
		cp -f ${SUDOERSFILE} /etc/sudoers-without-xwhep
#		echo ${SUDOERSENTRY} >> ${SUDOERSFILE}
#		echo ${SUDOERSENTRY2} >> ${SUDOERSFILE}
		echo << SUDOERSEOF >> ${SUDOERSFILE}
# Created by xwhep on `date`

# User rules for ubuntu
${SUDOERSENTRY}
${SUDOERSENTRY2}
xwhep ALL=(ALL) NOPASSWD: /bin/su
SUDOERSEOF

		chmod 440 $SUDOERSFILE
	fi
else
    echo "SYSLOGIN variable is not set; this package will run as root ; this is not a good idea" >> ${LOG}  2>&1 
fi

SHAREDAPPS=""
#
# share VirtualBox, if available
#
if [ -x ${VBHL} ] ; then
	SHAREDAPPS=${VBAPPNAME}
fi
#
# share Docker, if available
#
if [ -x ${DOCKERPATH} ] ; then
	if [ -z ${SHAREDAPPS} ] ; then
	    SHAREDAPPS=${DOCKERAPPNAME}
	else
	    SHAREDAPPS="${SHAREDAPPS},${DOCKERAPPNAME}"
	fi
fi

[ -z ${SHAREDAPPS} ] || echo "sharedapps=${SHAREDAPPS}" >> $CONFILE


# don't forget the ending dot
update-rc.d ${PROG} stop 99 3 4 5 .  >> ${LOG}  2>&1
update-rc.d -f ${PROG} remove  >> ${LOG}  2>&1
update-rc.d ${PROG} defaults 99  >> ${LOG}  2>&1

${INITD}/${PROG} start >> ${LOG}  2>&1


echo "XtemWeb-HEP ${PROG} ${WHAT} done" >> ${LOG}  2>&1 
