/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_MacSaver */

#ifndef _Included_xtremweb_archdep_MacSaver
#define _Included_xtremweb_archdep_MacSaver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_MacSaver
 * Method:    running
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_MacSaver_running
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
