/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_WinSaver */

#ifndef _Included_xtremweb_archdep_WinSaver
#define _Included_xtremweb_archdep_WinSaver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    screenSaverRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xtremweb_archdep_WinSaver_screenSaverRunning
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    lowPowerActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xtremweb_archdep_WinSaver_lowPowerActive
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    disableLowPower
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_WinSaver_disableLowPower
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    enableLowPower
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_WinSaver_enableLowPower
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    powerOffActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xtremweb_archdep_WinSaver_powerOffActive
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    disablePowerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_WinSaver_disablePowerOff
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    enablePowerOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_WinSaver_enablePowerOff
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    lowPowerTimeOut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_WinSaver_lowPowerTimeOut
  (JNIEnv *, jclass);

/*
 * Class:     xtremweb_archdep_WinSaver
 * Method:    powerOffTimeOut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_WinSaver_powerOffTimeOut
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
