/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_XWUtilImpl */

#ifndef _Included_xtremweb_archdep_XWUtilImpl
#define _Included_xtremweb_archdep_XWUtilImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    isRunning
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xtremweb_archdep_XWUtilImpl_isRunning
  (JNIEnv *, jobject, jint);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getPid
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getSpeedProc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getSpeedProc
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getProcModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xtremweb_archdep_XWUtilImpl_getProcModel
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getTotalMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xtremweb_archdep_XWUtilImpl_getTotalMem
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getTotalSwap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xtremweb_archdep_XWUtilImpl_getTotalSwap
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getCpuLoad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getCpuLoad
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getProcessLoad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getProcessLoad
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    raz
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWUtilImpl_raz
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getGid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getGid
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWUtilImpl
 * Method:    getUid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWUtilImpl_getUid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
