#!/bin/bash
# 
# Usage :

#TRUST=30;
#PUBLISH_PERIOD=2 #Every X minutes

#availableWorkers=9

if [ -z $TRUST ]; then
    echo "TRUST shouldn't be empty"
	exit
fi

if [ $TRUST -lt 10 ]; then
	TRUST=10
fi

expectedWorkers=$(($TRUST/10))


echo 'Starting publishing orders if necessary with trust='$TRUST
while true
do 
    availableWorkers=$(mysql -h db -u$DBUSER -p$DBPASS iexec -se "SELECT count(*) FROM hosts WHERE lastAlive >= (NOW() - INTERVAL 5 MINUTE) AND marketorderUID IS NULL AND contributionstatus='UNAVAILABLE';")

	if ! [[ $availableWorkers =~ ^[0-9]+$ ]]; then
	    echo "mysql request failed"
		continue
	fi

	if [ $availableWorkers -le 0 ]; then
		echo "No orders to publish"
		continue
	fi

	ordersToPublish=$(($availableWorkers/$expectedWorkers))

	if [ $ordersToPublish -le 0 ]; then
		echo "No orders to publish"
		continue
	fi

	echo "Could publish $ordersToPublish orders"


	######## WORKERDROP ONLY #####
	ordersToPublish=1
	echo "But publish only 1 order"
	

	for i in $(seq 1 $ordersToPublish)
	do
		if [ -z $CATEGORY ]; then
			CATEGORY=$(shuf -i 3-5 -n 1)
		fi
		if [ -z $PRICE ]; then
			PRICE=$(shuf -i 8-16 -n 1)
		fi
		pool='scheduler'
		echo 'POST /sendmarketorder?pool='$pool'&category='$CATEGORY'&price='$PRICE'&trust='$TRUST
		request='https://'$pool':443/sendmarketorder?XMLDESC=<marketorder><direction>ASK</direction><categoryid>'$CATEGORY'</categoryid><trust>'$TRUST'</trust><price>'$PRICE'</price><volume>1</volume></marketorder>'
		echo $request
		curl --request GET --insecure --user $ADMINLOGIN':'$ADMINPASSWORD --url $request
		echo
		sleep 10
	done

	period=$((60*$PUBLISH_PERIOD))
	echo "Waiting $period sec"
	sleep $period
    
done












