server:
  port: 8080 #8080 is default
  contextPath: /

web3j:
  client-address: ${ethNode:http://localhost:8545} #default
  admin-client: false #default

ethereum:
  start-block: 740
  address:
    iexecHub: ${iexecHub:0x9b69ef69a739c926558c81a402e5cdd6e5efbcfa}

wallet:
    folder: "./src/main/resources/wallet"

scheduler:
  address: "0x8bd535d49b095ef648cd85ea827867d358872809"
  wallet:
    filename: "UTC--2018-02-14T08-32-12.500000000Z--8bd535d49b095ef648cd85ea827867d358872809.json"
    password: "whatever"


#Mock values
mock:
  worker-result:
    "iExec the wanderer" #hash 0x2fa3c6dc29e10dfc01cea7e9443ffe431e6564e74f5dcf4de4b04f2e5d343d70
  createWorkerPool:
    name: "myWorkerPool"
    subscriptionLockStakePolicy: 0
    subscriptionMinimumStakePolicy: 0
    subscriptionMinimumScorePolicy: 0
  changeWorkerPoolPolicy:
    _newStakeRatioPolicy:
    _newSchedulerRewardRatioPolicy:
    _newResultRetentionPolicy:
    _newSubscriptionMinimumStakePolicy:
    _newSubscriptionMinimumScorePolicy:

  callForContribution:
    worker: "0x70a1bebd73aef241154ea353d6c8c52d420d4f5b"
    enclaveChallenge: "0"
  finalizeWork:
    stdout: "aStdout"
    stderr: "aStderr"
    uri: "anUri"

workerpool-policy:
  mode: 1 #BLACKLIST
  list:
    - "0x000000000000000000000000000000000000bad1"
    - "0x000000000000000000000000000000000000bad2"





