server:
  port: 8080 #8080 is default
  contextPath: /

web3j:
  client-address: ${ethNode:http://localhost:8545} #default
  admin-client: false #default

ethereum:
  startBlock: 0
  address:
    iexecHub: ${iexecHub:0x7d4f818724f283396dd01275a19ee2a211e7ff38}

wallet:
    folder: "./src/main/resources/wallet"

scheduler:
  address: "0x8bd535d49b095ef648cd85ea827867d358872809"
  wallet:
    filename: "UTC--2018-02-14T08-32-12.500000000Z--8bd535d49b095ef648cd85ea827867d358872809.json"
    password: "whatever"

workerpool:
  name: "myWorkerPool"              #unchangeable after creation
  subscriptionLockStakePolicy: 0    #unchangeable after creation
  subscriptionMinimumStakePolicy: 0
  subscriptionMinimumScorePolicy: 0
  stakeRatioPolicy: 30
  schedulerRewardRatioPolicy: 1
  resultRetentionPolicy: 7
  mode: 1
  list:
    - "0x000000000000000000000000000000000000bad1"
    - "0x000000000000000000000000000000000000bad2"
    - "0x55b541c70252aa3eb1581b8e74ce1ec17126b33a"

#Mock values
mock:
  workerResult:
    "iExec the wanderer" #hash 0x2fa3c6dc29e10dfc01cea7e9443ffe431e6564e74f5dcf4de4b04f2e5d343d70
  callForContribution:
    worker: "0x70a1bebd73aef241154ea353d6c8c52d420d4f5b"
    enclaveChallenge: "0"
  finalizeWork:
    stdout: "aStdout"
    stderr: "aStderr"
    uri: "anUri"







