#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postinst"
LOG="/var/log/xwhep-server.log"
INSTALLDIR="/opt/xwhep-server-@XWVERSION@"
BINDIR="$INSTALLDIR/bin"
VARXWHEP="/var/xwhep/server"
PROG="xtremweb.server"
XWGANGLIA="xtremweb.ganglia"
INITD="/etc/init.d"
SYSLOGIN="@SYSTEMUSER@"

touch $LOG
date >> $LOG  2>&1 
echo "XtemWeb-HEP $PROG $WHAT @XWVERSION@" >> $LOG  2>&1 

rm -f $INITD/$PROG >> $LOG 2>&1
ln -s $BINDIR/$PROG $INITD/$PROG >> $LOG 2>&1

rm -f $INITD/$XWGANGLIA >> $LOG 2>&1
ln -s $BINDIR/$XWGANGLIA $INITD/$XWGANGLIA >> $LOG 2>&1

if [ "X$SYSLOGIN" != "X" ] ; then 
    chown -R $SYSLOGIN.$SYSLOGIN $INSTALLDIR >> $LOG 2>&1
    chown -R $SYSLOGIN.$SYSLOGIN $VARXWHEP >> $LOG 2>&1
else
    echo "SYSLOGIN variable is not set; this package will run as root; this is not agood idea" >> $LOG  2>&1 
fi

# don't forget the ending dot
update-rc.d $PROG stop 99 3 4 5 . >> $LOG  2>&1
update-rc.d -f $PROG remove >> $LOG  2>&1
update-rc.d $PROG defaults 99 >> $LOG  2>&1

#
# Since Sept 20th, 2013
#  there is a server configuration package
#  that last starts services
#
echo "XtemWeb-HEP $PROG $WHAT : since 09/20/2013 services should be started by the server configuration package" >> $LOG  2>&1 

#$INITD/$PROG start

update-rc.d $XWGANGLIA stop 99 3 4 5 . >> $LOG  2>&1
update-rc.d -f $XWGANGLIA remove >> $LOG  2>&1
update-rc.d $XWGANGLIA defaults 99 >> $LOG  2>&1

#$INITD/$XWGANGLIA start


echo "XtemWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
