#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postrm"
LOG="/var/log/xwhep-server.log"
INSTALLDIR="/opt/xwhep-server-@XWVERSION@"
BINDIR="$INSTALLDIR/bin"
PROG="xtremweb.server"
XWGANGLIA="xtremweb.ganglia"
SYSLOGIN="@SYSTEMUSER@"
VERSION="@XWVERSION@"

touch $LOG
date >> $LOG  2>&1 
echo "XtemWeb-HEP $PROG $WHAT @XWVERSION@" >> $LOG  2>&1 

ls -l /etc/init.d/$PROG | grep $VERSION 2>&1
[ $? -eq 0 ] && rm -f /etc/init.d/$PROG >> $LOG  2>&1

ls -l /etc/init.d/$XWGANGLIA | grep $VERSION 2>&1
[ $? -eq 0 ] && rm -f /etc/init.d/$XWGANGLIA >> $LOG  2>&1

#if [ "X$SYSLOGIN" != "X" ] ; then 
#    deluser $SYSLOGIN >> $LOG  2>&1
#    delgroup $SYSLOGIN >> $LOG  2>&1
#fi

rm -Rf /tmp/xtremweb.ganglia* >> $LOG  2>&1
rm -Rf /tmp/xtremweb.server* >> $LOG  2>&1
rm -Rf /tmp/XW.SERVER* >> $LOG  2>&1
rm -Rf $INSTALLDIR >> $LOG  2>&1

update-rc.d -f $PROG remove >> $LOG  2>&1
update-rc.d -f $XWGANGLIA remove >> $LOG  2>&1

echo "XtemWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
