# READ THE CONFIG DOCUMENTATION AT:
# https://github.com/paritytech/parity-bridge/#configuration

# ACTION REQUIRED: set to your authority address
address = "0x0513425AE000f5bAEaD0ed485ED8c36E737e3586"

estimated_gas_cost_of_withdraw = "200000"

# limits total balance on `main` and therefore total ether that could get lost
# if the bridge is faulty or compromised in any way!
# set to `"0"` to disable limit (not recommended at this point)
# currently set to 10 ether.
max_total_main_contract_balance = "10000000000000000000"

# limit `msg.value` for a single deposit into the main contract.
# set to `"0"` to disable limit (not recommended at this point)
# currently set to 1 ether.
max_single_deposit_value = "1000000000000000000"

[main]
# ACTION REQUIRED: set the the url of the parity node that has `main.account` unlocked
http = "http://localhost:8545"


# ACTION REQUIRED: for test deployment set this to 12
required_confirmations = 0


[main.contract]
# READ THE CONFIG DOCUMENTATION AT:
# https://github.com/paritytech/parity-bridge/#configuration
bin = "../compiled_contracts/MainBridge.bin"



[side]
# ACTION REQUIRED: set the the url of the parity node that has `side.account` unlocked
http = "http://localhost:8545"
# ACTION REQUIRED: for test deployment set this to 12
required_confirmations = 0


[side.contract]
# READ THE CONFIG DOCUMENTATION AT:
# https://github.com/paritytech/parity-bridge/#configuration
bin = "../compiled_contracts/SideBridge.bin"

[authorities]
# ACTION REQUIRED: set this to the addresses of the authority list
accounts = [
	"0x0513425AE000f5bAEaD0ed485ED8c36E737e3586",
]
# ACTION REQUIRED: set this to a (super-)majority of `authorities.accounts`
# example: set to 3 for 5 authorities. set to 7 for 10 authorities
required_signatures = 1

[transactions]
# `gas` below should be good defaults for test deployment.
# ACTION REQUIRED: you have to set `gas_price` for each transaction
# if your authority can't do free transactions on the chain.
# `gas_price` might need adjustment once in a while.

# these happen on `main`:
#main_deploy = { gas = "1000000" , gas_price = "0" }
main_deploy = { gas = "1000000" , gas_price = "20000000000" }
withdraw_relay = { gas = "150000" , gas_price = "20000000000" }

# these happen on `side`:
#side_deploy = { gas = "3000000" , gas_price = "0" }
side_deploy = { gas = "3000000" , gas_price = "20000000000" }
deposit_relay = { gas = "150000" , gas_price = "20000000000" }
withdraw_confirm = { gas = "300000" , gas_price = "20000000000" }

