#!/bin/sh


cat << EOF
**********************************************************
Attention, on suppose que :
  - IP=134.158.90.77
  - network @=134.158.90.0
**********************************************************
EOF

#sudo yum localinstall  ~lodygens/Downloads/rubygem-bunny-0.6.0-2.el5.noarch.rpm 
sudo yum install stratuslab-cli-sysadmin stratuslab-cli-user -y --nogpgcheck
#export FRONTEND_IP="127.0.0.1"
export FRONTEND_IP="134.158.90.77"
echo $FRONTEND_IP 
sudo stratus-config default_gateway $FRONTEND_IP
sudo stratus-config frontend_ip $FRONTEND_IP
sudo stratus-config share_type nfs
sudo stratus-config node_system fedora
sudo stratus-config frontend_system fedora
#sudo stratus-config one_private_network 192.168.0.0
#sudo stratus-config one_private_network_addr 192.168.0.1
sudo stratus-config node_bridge_configure False
sudo stratus-config persistent_disk False
sudo stratus-config default_gateway $FRONTEND_IP
sudo stratus-config frontend_ip $FRONTEND_IP
stratus-config one_local_network_addr 192.168.16.43 192.168.16.44 192.168.16.45 192.168.16.46 192.168.16.47 192.168.16.48 192.168.16.49 192.168.16.50 192.168.16.51
stratus-config one_local_network_mac 0a:0a:86:9e:50:2b 0a:0a:86:9e:50:2c 0a:0a:86:9e:50:2d 0a:0a:86:9e:50:2e 0a:0a:86:9e:50:2f 0a:0a:86:9e:50:30 0a:0a:86:9e:50:31 0a:0a:86:9e:50:32 0a:0a:86:9e:50:33

stratus-config nat False
stratus-config persistent_disk False

#stratus-config dhcp True
#stratus-config dhcp_subnet 134.158.90.0
#stratus-config dhcp_netmask 255.255.255.0
#stratus-config dhcp_lease_time 3600

#stratus-config dhcp_one_local_network True
#stratus-config dhcp_one_local_network_subnet 192.168.16.0
#stratus-config dhcp_one_local_network_broadcast 192.168.16.255
#stratus-config dhcp_one_local_network_netmask 255.255.255.0
#stratus-config dhcp_one_local_network_routers 192.168.16.2
#stratus-config dhcp_one_local_network_domain_name stratuslab-gk5.fr
#stratus-config dhcp_one_local_network_domain_name_servers 134.158.91.80

stratus-config dhcp False
rm -f dhcpd.conf
cat << EOF > dhcpd.conf

ddns-update-style none;
ignore unknown-clients;
ignore bootp;

shared-network StratusLab-LAN {
  subnet 134.158.90.0 netmask 255.255.255.0 {
  }
  subnet 192.168.16.0 netmask 255.255.255.0 {
   option routers 192.168.16.2;
  }
}

group {

  option broadcast-address 192.168.16.255;
  option subnet-mask 255.255.255.0;
  option routers 192.168.16.2;
  option domain-name "stratuslab-gk5.fr";
  option domain-name-servers 134.158.91.80;

  host onelocalnetwork-vm0 {
    hardware ethernet 0a:0a:86:9e:50:2b;
    fixed-address 192.168.16.43;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm1 {
    hardware ethernet 0a:0a:86:9e:50:2c;
    fixed-address 192.168.16.44;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm2 {
    hardware ethernet 0a:0a:86:9e:50:2d;
    fixed-address 192.168.16.45;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm3 {
    hardware ethernet 0a:0a:86:9e:50:2e;
    fixed-address 192.168.16.46;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm4 {
    hardware ethernet 0a:0a:86:9e:50:2f;
    fixed-address 192.168.16.47;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm5 {
    hardware ethernet 0a:0a:86:9e:50:30;
    fixed-address 192.168.16.48;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm6 {
    hardware ethernet 0a:0a:86:9e:50:31;
    fixed-address 192.168.16.49;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm7 {
    hardware ethernet 0a:0a:86:9e:50:32;
    fixed-address 192.168.16.50;
    max-lease-time 3600;
  }

  host onelocalnetwork-vm8 {
    hardware ethernet 0a:0a:86:9e:50:33;
    fixed-address 192.168.16.51;
    max-lease-time 3600;
  }
}
EOF


cp -f dhcpd.conf /etc/dhcp/

yum -y --nogpgcheck install dhcp

service dhcpd restart


iptables -nL -t filter
iptables -nL -t nat
iptables -nL -t mangle
iptables -nL -t raw
iptables-save -t filter
iptables -t filter -D INPUT -s 127.0.0.1 -p tcp -m tcp --dport 2633 -j ACCEPT
iptables -t filter -D INPUT -p tcp -m tcp --dport 2633 -j REJECT --reject-with icmp-port-unreachable
iptables -t filter -A INPUT -s 127.0.0.1 -p tcp -m tcp --dport 2633 -j ACCEPT
iptables -t filter -A INPUT -p tcp -m tcp --dport 2633 -j REJECT --reject-with icmp-port-unreachable
iptables-save -t filter
iptables-save -t nat
iptables -t nat -D POSTROUTING -s 192.168.16.0/255.255.255.0 -d ! 192.168.16.0/255.255.255.0 -j MASQUERADE
iptables -t filter -D FORWARD -d 192.168.16.0/255.255.255.0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -D FORWARD -d 192.168.16.0/255.255.255.0 -j ACCEPT
iptables -t nat -A POSTROUTING -s 192.168.16.0/255.255.255.0 -d ! 192.168.16.0/255.255.255.0 -j MASQUERADE
iptables -t filter -A FORWARD -d 192.168.16.0/255.255.255.0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -d 192.168.16.0/255.255.255.0 -j ACCEPT
cp -fp /etc/sysconfig/iptables /etc/sysconfig/iptables.LAST
export FRONTEND_IP=134.158.90.77



service sshd restart

ssh-keygen
ssh-copy-id localhost

stratus-install -vvv
stratus-install -n 127.0.0.1 -vvv



yum install -y --nogpgcheck stratuslab-marketplace

cat << EOF
**********************************************************
Attention : reste a faire : enlever le montage NFS et effacer dans fstab

umount -fl /var/lib/one
Et edit /etc/fstab et /etc/exports


Puis

su - oneadmin --command="onevnet list"
su - oneadmin --command="onevnet show ???"


stratus-run-instance -u oneadmin -p oneadmin --endpoint=localhost --local-ip <id market stratuslab>

**********************************************************

EOF



