#!/bin/sh

# Copyright [2018] [CNRS] Simon Dadoun
# License : Apache 2
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
#
#
#



#  ******************************************************************
#  File    : edgiar_downloadapp.sh
#  Date    : Dec 9th, 2011
#  Author  : Simon Dadoun
# 
#  OS      : Linux
# 
#  Purpose : this script creates a new LiveCD
# 
#  !!!!!!!!!!!!!!!!    DO NOT EDIT    !!!!!!!!!!!!!!!!
#  Remarks : this script is auto generated by install process
#  ******************************************************************

app_name=$1

rm -rf xwapps; mkdir xwapps; cd xwapps

if [ "$app_name" == "" ]; then APPS=`xwapps`; else APPS=`xwapps | grep $app_name`; fi

#awk print first column, sed remove leading UID=', sed remove ending ',
#xwapps | awk '{print $1}' | sed "s/UID='//"  | sed "s/',//"
APPS=`echo $APPS | awk '{print $1}' | sed "s/UID='//"  | sed "s/',//"`

#echo "APPS="$APPS

for appUID in $APPS
do
  #name_cmd="xwapps $appUID --xwformat xml | grep -Po '^.*?\K(?<=name=\").*?(?=\")'"
  name_cmd="xwapps $appUID --xwformat xml | sed 's/name=\"/&\n/;s/.*\n//;s/\"/\n&/;s/\n.*//;1,2d;4d'"
  app_name=`eval $name_cmd`
  #echo $name_cmd
  echo "App "$app_name

  for cpu in basedirinuri linux_ix86uri linux_amd64uri linux_x86_64uri win32_ix86uri javauri
  do
    #cpu_cmd="xwapps "$appUID" --xwformat xml | grep -Po '^.*?\K(?<="$cpu"=\").*?(?=\")'"
    cpu_cmd="xwapps "$appUID" --xwformat xml | sed 's/"$cpu"=\"/&\n/;s/.*\n//;s/\"/\n&/;s/\n.*//;1,2d;4d'"
    #echo "cpu_cmd="$cpu_cmd
    cpu_uri=`eval $cpu_cmd`
    echo $cpu_uri | grep 'app uid'
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then cpu_uri=""; fi
    #echo "cpu_uri="$cpu_uri
    if [ -n "$cpu_uri" ]; then
      down_cmd="xwdownload $cpu_uri"
      eval $down_cmd
      RETVAL=$?
      #echo "RETVAL="$RETVAL
      if [ $RETVAL -ne 0 ]; then
        echo "!! ERROR !! for app "$app_name" and cpu "$cpu;
      fi
    fi
  done

done

