version: '3.4'
services:
  order-publisher:
    image: iexechub/iexec-order-publisher:${ORDER_PUBLISHER_IMAGE_VERSION}
    container_name: order-publisher
    restart: always
    environment:
      - DBUSER=${MYSQL_USER_LOGIN}
      - DBPASS=${MYSQL_USER_PASSWORD}
      - ADMINLOGIN=${ADMINLOGIN}
      - ADMINPASSWORD=${ADMINPASSWORD}
      - TRUST=${ORDER_PUBLISHER_TRUST}
      - PUBLISH_PERIOD=${ORDER_PUBLISHER_PUBLISH_PERIOD}
      - CATEGORY=${ORDER_PUBLISHER_CATEGORY}
      - PRICE=${ORDER_PUBLISHER_PRICE}
      - PRICEMIN=${ORDER_PUBLISHER_PRICEMIN}
      - PRICEMAX=${ORDER_PUBLISHER_PRICEMAX}
networks:
  default:
    external:
      name: iexec-scheduler_iexec-net
