/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_PortMapper */

#ifndef _Included_xtremweb_archdep_PortMapper
#define _Included_xtremweb_archdep_PortMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_PortMapper
 * Method:    gettcpport
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_PortMapper_gettcpport
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xtremweb_archdep_PortMapper
 * Method:    getudpport
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_PortMapper_getudpport
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xtremweb_archdep_PortMapper
 * Method:    getGid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_PortMapper_getGid
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_PortMapper
 * Method:    getUid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_PortMapper_getUid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
