/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_XWInterruptsWin32 */

#ifndef _Included_xtremweb_archdep_XWInterruptsWin32
#define _Included_xtremweb_archdep_XWInterruptsWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_XWInterruptsWin32
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_xtremweb_archdep_XWInterruptsWin32_initialize
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWInterruptsWin32
 * Method:    readKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWInterruptsWin32_readKey
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWInterruptsWin32
 * Method:    readMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xtremweb_archdep_XWInterruptsWin32_readMouse
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
