/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtremweb_archdep_XWTracerImpl */

#ifndef _Included_xtremweb_archdep_XWTracerImpl
#define _Included_xtremweb_archdep_XWTracerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtremweb_archdep_XWTracerImpl
 * Method:    collectNodeConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWTracerImpl_collectNodeConfig
  (JNIEnv *, jobject, jint);

/*
 * Class:     xtremweb_archdep_XWTracerImpl
 * Method:    checkNodeState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWTracerImpl_checkNodeState
  (JNIEnv *, jobject, jint);

/*
 * Class:     xtremweb_archdep_XWTracerImpl
 * Method:    checkNetwork
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWTracerImpl_checkNetwork
  (JNIEnv *, jobject, jint);

/*
 * Class:     xtremweb_archdep_XWTracerImpl
 * Method:    fermera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWTracerImpl_fermera
  (JNIEnv *, jobject);

/*
 * Class:     xtremweb_archdep_XWTracerImpl
 * Method:    setOutputDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xtremweb_archdep_XWTracerImpl_setOutputDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
