#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.
#
#




#  ******************************************************************
#  File    : xwapps
#  Date    : Thu Dec 21 2006
#  Author  : Oleg Lodygensky (lodygens -a-t- lal.in2p3.fr)
# 
#  OS      : Linux
# 
#  Purpose : a script to retreive applications from server
# 
#  !!!!!!!!!!!!!!!!    DO NOT EDIT    !!!!!!!!!!!!!!!!
#  Remarks : this script is auto generated by install process
#  ******************************************************************

#=============================================================================
# Function  usage
#=============================================================================
usage() {
	cat <<EOFUSAGE

Usage : $0 -u dbuser -p dbpassword [-d databasename] [-n nbhosts]
	This insert <nbhosts> new machine
	Default database name = "xtremweb"
	Default nbhost        = 5

EOFUSAGE

	exit 0
}

#=============================================================================
# Function  fatal
#=============================================================================
fatal() {
	cat <<EOFMSG
- * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! * -
FATAL : $1
- * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! * -
EOFMSG

	exit 1
}	

#=============================================================================
# main 
#=============================================================================

# Test uuidgen
type uuidgen > /dev/null 2>&1 || fatal "UUIDGEN is not installed; please install it and/or correct your \$PATH env variable."

# Test uuidgen
type mysql > /dev/null 2>&1 || fatal "mysql is not installed; please install it and/or correct your \$PATH env variable."

MYSQLOPTS=""
DBNAME="xtremweb"
NBHOSTS=5

while [ $# -gt 0 ]; do
	case $1 in
		"-h" | "--help" | "--h" | "-?" )
			usage
			;;
		"-u" )
			shift
			MYSQLOPTS="$MYSQLOPTS -u $1"
			;;
		"-p" )
			shift
			MYSQLOPTS="$MYSQLOPTS --password $1"
			;;
		"-d" )
			shift
			DBNAME=$1
			;;
		"-n" )
			shift
			NBHOSTS=$1
			;;
	esac
	shift
done

MYSQLOPTS="$MYSQLOPTS $DBNAME"

WORKER_OWNER_UID=`mysql $MYSQLOPTS -B -e "select uid,login from users where rights='WORKER_USER'" | tail -1 | cut -f 1`
if [ $? -ne 0 ] ; then
	fatal "\"mysql $MYSQLOPTS -e ''\" failed.  Please verify if MySQL is correctly installed."
fi

OSES[0]="MACOSX"
OSES[1]="LINUX"
OSES[2]="WIN32"

CPUS[0]="AMD64"
CPUS[1]="IX86"
CPUS[2]="X86_64"
CPUS[3]="ARM"
CPUS[4]="PPC"


for ((i=0;i<NBHOSTS;i++)) ; do

	OS=${OSES[$((i%3))]}
	CPU=${CPUS[$((i%5))]}

	echo $i $OS $CPU

	WORKER_UID=`uuidgen`
	mysql $MYSQLOPTS -B -e "insert into hosts (uid,owneruid,name,ipaddr,nbjobs,accessrights,lastalive,version,osid,os,cputypeid,cputype)       \
							values (\"$WORKER_UID\",\"$WORKER_OWNER_UID\",'pouet','127.0.0.$i',\"$i\",'1877', now(),'10.2.0-head', \
			               			(select osId from oses where osName = \"$OS\"),\"$OS\",    \
			               			(select cpuTypeId from cputypes where cpuTypeName = \"$CPU\"),\"$CPU\"     \
			               		)"
done

mysql $MYSQLOPTS -e "select uid,owneruid,name,lastalive,accessrights,version,os,cputype,ipaddr,nbjobs from hosts"
