#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.
#
#




#  ******************************************************************
#  File    : xwapps
#  Date    : Thu Dec 21 2006
#  Author  : Oleg Lodygensky (lodygens -a-t- lal.in2p3.fr)
# 
#  OS      : Linux
# 
#  Purpose : a script to retreive applications from server
# 
#  !!!!!!!!!!!!!!!!    DO NOT EDIT    !!!!!!!!!!!!!!!!
#  Remarks : this script is auto generated by install process
#  ******************************************************************

#=============================================================================
# Function  usage
#=============================================================================
usage() {
	cat <<EOFUSAGE

Usage : $0 -u dbuser -p dbpassword -a appname [-d databasename] [-n nbjobs] [-o user_login]
	This insert <nbjobs> new jobs for application "appname for user user_login"
	Default database name = "xtremweb"
	Default nbhost        = 5
	Default user login    = "admin"

EOFUSAGE

	exit 0
}

#=============================================================================
# Function  fatal
#=============================================================================
fatal() {
	cat <<EOFMSG
- * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! * -
FATAL : $1
- * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! * -
EOFMSG

	exit 1
}	

#=============================================================================
# main 
#=============================================================================

# Test uuidgen
type uuidgen > /dev/null 2>&1 || fatal "UUIDGEN is not installed; please install it and/or correct your \$PATH env variable."

# Test uuidgen
type mysql > /dev/null 2>&1 || fatal "mysql is not installed; please install it and/or correct your \$PATH env variable."

MYSQLOPTS=""
DBNAME="xtremweb"
NBJOBS=5
APPNAME=""
USERLOGIN="admin"

while [ $# -gt 0 ]; do
	case $1 in
		"-h" | "--help" | "--h" | "-?" )
			usage
			;;
		"-a" )
			shift
			APPNAME=$1
			;;
		"-u" )
			shift
			MYSQLOPTS="$MYSQLOPTS -u $1"
			;;
		"-p" )
			shift
			MYSQLOPTS="$MYSQLOPTS --password $1"
			;;
		"-d" )
			shift
			DBNAME=$1
			;;
		"-n" )
			shift
			NBJOBS=$1
			;;
		"-o" )
			shift
			USERLOGIN=$1
			;;
	esac
	shift
done

[ -z $APPNAME ] && fatal "You must provide an application name"

MYSQLOPTS="$MYSQLOPTS $DBNAME"

JOB_OWNER_UID=`mysql $MYSQLOPTS -B -e "select uid,login from users where login=\"$USERLOGIN\"" | tail -1 | cut -f 1`
if [ $? -ne 0 ] ; then
	fatal "Can't retrieve 'admin' user"
fi
[ -z $JOB_OWNER_UID ] && fatal "Can't retrieve 'admin' user"


APPTEST_UID=`mysql $MYSQLOPTS -B -e "select uid,name from apps where name=\"$APPNAME\" " | tail -1 | cut -f 1`
if [ $? -ne 0 ] ; then
	fatal "Can't retrieve \"$APPNAME\" application"
fi
[ -z $APPTEST_UID ] && fatal "Can't retrieve \"$APPNAME\" application"


for ((i=0;i<NBJOBS;i++)) ; do

        STATUS="COMPLETED"
	if [ $((i%5)) -eq 0 ] ; then
		STATUS="RUNNING"
	fi
	if [ $((i%8)) -eq 0 ] ; then
		STATUS="ERROR"
	fi

	echo "$i $STATUS"

	WORK_UID=`uuidgen`
	mysql $MYSQLOPTS -B -e "insert into works (uid,owneruid,accessrights,appuid,arrivaldate,statusid,status)       \
							values (\"$WORK_UID\",\"$JOB_OWNER_UID\",'1792', \"$APPTEST_UID\", now(), \
			               			(select statusid from statuses where statusName = \"$STATUS\"),\"$STATUS\"     \
			               		)"
done

mysql $MYSQLOPTS -e "select works.uid,works.status,apps.name,users.login from works,apps,users where works.appuid=apps.uid and works.owneruid=users.uid"
