#!/bin/bash
# 
# Usage : ./consumeOrders --chain=rinkeby --category=5 --owner='0x68ba0fC5E52e540778069113507507A012362cfD' --period=60

source ~/.nvm/nvm.sh

sdkEnv=/home/sdk-env

cd $sdkEnv

if [ ! -f $sdkEnv/iexec.json ]; then
    echo "iexec.json missing"
    exit
fi

for i in "$@"
do
case $i in
    -c=*|--chain=*)
    CHAIN_NAME="${i#*=}"
    shift
    ;;
    -cat=*|--category=*)
    CATEGORY="${i#*=}"
    shift
    ;;
    -o=*|--owner=*)
    WORKERPOOL_OWNER="${i#*=}"
    shift
    ;;
    -p=*|--period=*)
    PERIOD="${i#*=}"
    shift
    ;;
    *)
          # unknown option
    ;;
esac
done


case $CHAIN_NAME in
dev)
    CHAIN_ID=1337
    ;;
ropsten)
    CHAIN_ID=3
    ;;
rinkeby)
    CHAIN_ID=4
    ;;
kovan)
    CHAIN_ID=42
    ;;
mainnet)
    CHAIN_ID=1
    ;;
*)
    echo "Chain name unknown"
    exit
;;
esac


if [ -z $CHAIN_ID ]; then
	echo "Chain ID missing"
	exit
fi

if [ -z $CHAIN_NAME ]; then
	echo "Chain name missing"
	exit
fi

if [ -z $CATEGORY ]; then
	echo "Category missing"
	exit
fi

if [ -z $WORKERPOOL_OWNER ]; then
	echo "Workerpool owner missing"
	exit
fi

if [ -z $PERIOD ]; then
	echo "Consume period missing"
	exit
fi


iexec account show --chain $CHAIN_NAME


while true
do 
    request="https://gateway.iex.ec/orderbook?chainID=$CHAIN_ID&category=$CATEGORY"
    echo $request
	orders=$(curl --request GET --url $request | jq ".orders[] | select(.workerpoolOwner==\"$WORKERPOOL_OWNER\")" | jq -r '.marketorderIdx')

	for i in $orders
	do	
		echo "iexec order fill $i --chain $CHAIN_NAME --force"
        iexec order fill $i --chain $CHAIN_NAME --force
        break
	done
	echo "Waiting $PERIOD sec"
	sleep $PERIOD
done











