#!/bin/bash
#
# File : xwhep.server/installer/Ressources/postflight
#
# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


ERROK=0
ERRUSAGE=1
ERRFILE=2
ERRCONNECTION=3
ERRSTATE=4
ERRUSER=5

# since july
# the server runs as root...
SYSLOGIN="@SYSTEMUSER@"
PKG="xwhep.server"
PROG="xtremweb.server"
# this is the name defined in /Library/LaunchDaemons/xwhep.server.plist
LAUNCHNAME="fr.in2p3.lal.xwhep.server"
VARXWHEP="/var/xwhep/server"

HOST=`uname -a | cut -d ' ' -f 2`
LOGFILENAME=$PROG-$HOST.log
LOGFILE=/var/log/$LOGFILENAME
touch $LOGFILE

chmod +x /private/etc/$PKG/bin/*.sh
chmod +x /Applications/$PKG/bin/*.sh

mkdir -p $VARXWHEP >> $LOGFILE 2>&1


#clean old version
[ -d /private/etc/$PROG ] && rm -Rf /private/etc/$PROG
[ -d /Library/StartupItems/$PROG ] && rm -Rf /Library/StartupItems/$PROG
dscl . list /users/xtremweb
if [ $? -eq 0 ]; then
    /private/etc/$PKG/bin/rmuser.sh xtremweb >> $LOGFILE 2>&1
fi
dscl . list /users/xtremwebwrk
if [ $? -eq 0 ]; then
    /private/etc/$PKG/bin/rmuser.sh xtremwebwrk >> $LOGFILE 2>&1
fi
dscl . list /users/xtremwebsrv
if [ $? -eq 0 ]; then
    /private/etc/$PKG/bin/rmuser.sh xtremwebsrv >> $LOGFILE 2>&1
fi


echo "*****************************" >> $LOGFILE 2>&1
echo "* [`date`] [$PROG] INFO : installing $PROG"  >> $LOGFILE 2>&1

OSMAJOR="10"
OSMINOR="6"

OSVERSION=`sw_vers -productVersion`
if [ $? -eq 0 ] ; then
    OSMAJOR=`sw_vers -productVersion | cut -d '.' -f 1`
    OSMINOR=`sw_vers -productVersion | cut -d '.' -f 2`
else
    echo "* [`date`] [$PROG] ERROR : can't determine OS version (sw_vers not found)" >> $LOGFILE 2>&1
    echo "*****************************" >> $LOGFILE 2>&1
    return $ERRUSAGE
fi

if [ $OSMAJOR -lt 10 ] ; then
    echo "* [`date`] [$PROG] ERROR : Mac OS $OSMAJOR not supported" >> $LOGFILE 2>&1
    echo "*****************************" >> $LOGFILE 2>&1
    return $ERRUSAGE
fi

if [ ! ls -d /Library/Java/JavaVirtualMachines/jdk1.8*/Contents/Home ] ; then
    echo "* [`date`] [$PROG] ERROR : Can't find Java 1.8" >> $LOGFILE 2>&1
    echo "*****************************" >> $LOGFILE 2>&1
    return $ERRUSAGE
fi

echo "Installing $PKG" >> $LOGFILE 2>&1

if [ "X$SYSLOGIN" != "X" ] ; then 
    echo "* [`date`] [$PROG] INFO : SYSLOGIN = $SYSLOGIN" >> $LOGFILE 2>&1
    dscl . list /users/$SYSLOGIN
    if [ $? -ne 0 ] ; then
		maxid=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
		newid=$((maxid+1))
		sudo /private/etc/$PKG/bin/adduser.sh $SYSLOGIN $SYSLOGIN $newid staff >> $LOGFILE 2>&1
		if [ $? -ne 0 ] ; then
	    	echo "* [`date`] [$PROG] ERROR : can't add user $SYSLOGIN" >> $LOGFILE 2>&1
		    echo "*****************************" >> $LOGFILE 2>&1
		    exit $ERRUSER
		fi
    fi
else
    echo "* [`date`] [$PROG] ERROR : SYSLOGIN variable is not set" >> $LOGFILE 2>&1
    echo "*****************************" >> $LOGFILE 2>&1
    exit $ERRUSER
fi

#
# set user
#
TMPDATE=`date +%Y%m%d%H%M%S`
TMPNAME=xw_$TMPDATE
cat /Library/LaunchDaemons/$LAUNCHNAME.plist | sed "s/%SYSLOGIN%/$SYSLOGIN/" > /tmp/$TMPNAME
mv /tmp/$TMPNAME /Library/LaunchDaemons/$LAUNCHNAME.plist
rm -f /tmp/$TMPNAME
cat /Library/LaunchDaemons/$LAUNCHNAME.plist | sed "s/\/var\/log\/xwhep\.server\.log/\/var\/log\/$LOGFILENAME/" > /tmp/$TMPNAME
mv /tmp/$TMPNAME /Library/LaunchDaemons/$LAUNCHNAME.plist
rm -f /tmp/$TMPNAME
chown root:wheel /Library/LaunchDaemons/$LAUNCHNAME.plist >> $LOGFILE 2>&1
chmod 644 /Library/LaunchDaemons/$LAUNCHNAME.plist >> $LOGFILE 2>&1

echo "chown $SYSLOGIN:$SYSLOGIN $LOGFILE" >> $LOGFILE 2>&1
chown $SYSLOGIN:$SYSLOGIN $LOGFILE >> $LOGFILE 2>&1
echo "chown -R $SYSLOGIN:$SYSLOGIN /private/etc/$PKG/" >> $LOGFILE 2>&1
chown -R $SYSLOGIN:$SYSLOGIN /private/etc/$PKG/ >> $LOGFILE 2>&1
echo "chown -R $SYSLOGIN:$SYSLOGIN $VARXWHEP" >> $LOGFILE 2>&1
chown -R $SYSLOGIN:$SYSLOGIN $VARXWHEP >> $LOGFILE 2>&1

#
# we don't use Mac OS specific stuffs
#
#rm -f /Library/LaunchDaemons/$LAUNCHNAME.plist
rm -Rf /Library/StartupItems/$PKG >> $LOGFILE 2>&1
rm -f /private/etc/$PKG/bin/$PROG.pid >> $LOGFILE 2>&1


chmod +x /usr/local/bin/$PROG >> $LOGFILE 2>&1
#/usr/local/bin/$PROG start
launchctl load -w /Library/LaunchDaemons/$LAUNCHNAME.plist >> $LOGFILE 2>&1


echo "* [`date`] [$PROG] INFO : $PROG installed " >> $LOGFILE 2>&1
echo "*****************************" >> $LOGFILE 2>&1


#return $ERROK

#
# EOF
#
