#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postrm"
LOG="/var/log/xwhep-worker.log"
INSTALLDIR="/opt/xwhep-worker-@XWVERSION@"
BINDIR="$INSTALLDIR/bin"
PROG="xtremweb.worker"
SYSLOGIN=@XWUSER@
GROUPE=${SYSLOGIN}

USRBIN=/usr/bin
USRBINXWCREATEVDI=$USRBIN/xwcreatevdi
USRLOCALBINCREATEVDI=$USRLOCALBIN/createvdi
SUDOERS=/etc/sudoers

touch $LOG
date >> $LOG  2>&1 
echo "XtemWeb-HEP $PROG $WHAT @XWVERSION@" >> $LOG  2>&1 

rm -f /etc/init.d/$PROG >> $LOG  2>&1

rm -Rf /tmp/xtremweb.worker*
rm -Rf /tmp/xtremweb.monitor*
rm -Rf /tmp/PortMapper.jni*
rm -f /tmp/XwTracer.jni*
rm -f /tmp/XWUtil.jni*
rm -Rf /tmp/XW.WORKER*
rm -Rf $INSTALLDIR >> $LOG 2>&1

rm -f $USRBINXWCREATEVDI >> $LOG  2>&1
rm -f $USRLOCALBINCREATEVDI >> $LOG  2>&1
grep $SYSLOGIN $SUDOERS >> $LOG  2>&1
if [ $? -eq 0 ] ; then
	cat $SUDOERS | grep -v $SYSLOGIN > /tmp/xwsudoers
	mv -f /tmp/xwsudoers $SUDOERS
	chmod 440 $SUDOERS
fi

if [ "X$SYSLOGIN" != "X" ] ; then
    echo "Removing system login to run the middleware $SYSLOGIN" >> $LOG  2>&1

# since 12.2.8, we create as many users as available CPU in a single group
# see xtremweb.common.XWPropertyDefs#OSACCOUNT
# see xtremweb.Woker.ThreadLaunch#getNextOsAccount()
# see xtremweb.Woker.ThreaWork#getBinPath()

    nbCpu=$(cat /proc/cpuinfo | grep processor | wc -l)
    nbCpu=$(( nbCpu - 1 ))
    [ $nbCpu -lt 1 ]] && nbCpu=1
    i=0
    while [ $i -lt $nbCpu ] ; do
        USERLOGIN=${SYSLOGIN}${i}
        /usr/sbin/userdel -f $USERLOGIN >> $LOG  2>&1
        rm -Rf /home/$USERLOGIN >> $LOG  2>&1
    done

    /usr/sbin/userdel -f $SYSLOGIN >> $LOG  2>&1
    /usr/sbin/groupdel $SYSLOGIN >> $LOG  2>&1
    rm -Rf /home/$SYSLOGIN >> $LOG  2>&1

else
    echo "SYSLOGIN variable is not set; this package has run as root; this is not a good idea" >> $LOG  2>&1
fi

update-rc.d -f $PROG remove  >> $LOG  2>&1

echo "XtemWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
