#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="preinst"
LOG="/var/log/xwhep-server.log"
XW_INSTALLDIR="/opt/xwhep-server-@XWVERSION@"
VARXWHEP="/var/xwhep/server"
PROG="xtremweb.server"
SYSLOGIN=@XWUSER@

touch $LOG
date >> $LOG  2>&1 
echo "XtemWeb-HEP $PROG $WHAT @XWVERSION@" >> $LOG  2>&1 


if [ "X$SYSLOGIN" != "X" ] ; then 
    echo "Creating system login to run your server $SYSLOGIN" >> $LOG  2>&1 
    echo "(so that xwhep does not run with privileged account)" >> $LOG  2>&1 
    /usr/sbin/groupadd $SYSLOGIN >> $LOG  2>&1 
    /usr/sbin/useradd $SYSLOGIN -d /home/$SYSLOGIN -s /bin/bash -g $SYSLOGIN -m >> $LOG  2>&1 
#    addgroup $SYSLOGIN >> $LOG  2>&1
#    adduser --home /home/$SYSLOGIN --shell /bin/bash --ingroup $SYSLOGIN --disabled-password --disabled-login $SYSLOGIN >> $LOG  2>&1
else
    echo "SYSLOGIN variable is not set; this package will run as root; this is not a good idea" >> $LOG  2>&1 
fi


rm -Rf $XW_INSTALLDIR  >> $LOG  2>&1
mkdir -p $XW_INSTALLDIR  >> $LOG  2>&1
mkdir -p $VARXWHEP  >> $LOG  2>&1
cd $XW_INSTALLDIR  >> $LOG  2>&1

echo "XtemWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
